configfile: "cfg.yaml"

rule get_phone :
     input : ['phones.txt']
     output : ['myphone.txt']
     shell : "grep "+config['name']+" {input} > {output}"

rule get_address :
     input : ['addresses.txt']
     output : ['myaddress.txt']
     shell : "grep "+config['name']+" {input} > {output}"

rule get_data :
     input : ['myaddress.txt','myphone.txt']
     output : ['data.txt']
     shell : "cat {input[0]} > {output} && cat {input[1]} >> {output}"



