name: Build and deploy the Starterkit lessons website.

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: lessons-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Build the website
        run: uvx starterkit-ci build --source-dir . --allow-warnings

      - name: Check for dead links
        run: uvx starterkit-ci check --source-dir . --allow-warnings

      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: build
          path: build/html/

  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v7
        with:
          name: build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
